# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  - push
  - delete

jobs:
  publish-npm:
    runs-on: self-hosted
    steps:
      - run: npm publish
